# External executables

# Where is the project root folder?
ROOT_PREFIX := ../../../
# Includes and libraries
LIBS := $(shell pkg-config --libs-only-l opencv)
APPEND_OPENCV_LIBS := 1

# Define subprojects
SUB_PROJS :=

# Simple executables (i.e. having only the cpp file as a dependency)
EXE_TARGETS := main

# Library
LIB_SHORT_NAME := 7bga

# Precompiled objects
PRECOMPILED_OBJECTS := 

# Include main makefile
include $(ROOT_PREFIX)subproj_makefile.mk
