# External executables

# Where is the project root folder?
ROOT_PREFIX := ../
# Includes and libraries
LIBS := -lutils -lcvblob -lalgorithms -lticppd -llog -lmysqlcppconn
APPEND_OPENCV_LIBS := 1

# Define subprojects
SUB_PROJS :=

# Simple executables (i.e. having only the cpp file as a dependency)
EXE_TARGETS := prova prova_contour prova_port

# Library
LIB_SHORT_NAME := newdb

# Precompiled objects
PRECOMPILED_OBJECTS :=

# Include main makefile
include $(ROOT_PREFIX)subproj_makefile.mk
