# External executables

# Where is the project root folder?
ROOT_PREFIX := ../
# Includes and libraries
LIBS := -lutils -llog -lticppd

# Define subprojects
SUB_PROJS :=

# Simple executables (i.e. having only the cpp file as a dependency)
EXE_TARGETS := prova

# Library
LIB_SHORT_NAME := xmlconfig

# Precompiled objects
PRECOMPILED_OBJECTS :=

# Include main makefile
include $(ROOT_PREFIX)subproj_makefile.mk
