# External executables

# Where is the project root folder?
ROOT_PREFIX := ../../
# Includes and libraries
LIBS :=

# Define subprojects
SUB_PROJS :=	GaussianMixtureModel \
		APMM2 \
		IntrinsicModel \
		WaveBack \
		Vibe2 \
		CodeBook \
		XMLDetection \
		Adaboost \
		Xbe \
		BGSLibrary
		#BayesMarkov \

# Simple executables (i.e. having only the cpp file as a dependency)
EXE_TARGETS := 

# Library
LIB_SHORT_NAME := detection

# Precompiled object
PRECOMPILED_OBJECTS := 

# Include main makefile
include $(ROOT_PREFIX)subproj_makefile.mk
