# External executables

# Where is the project root folder?
ROOT_PREFIX := ../
# Includes and libraries
LIBS := -lblobproc -ltrack -lutils -llog -lcvblob -lsigar
APPEND_OPENCV_LIBS=1

# Define subprojects
SUB_PROJS :=

# Simple executables (i.e. having only the cpp file as a dependency)
EXE_TARGETS := prova prova_hist prova_bayes

# Library
LIB_SHORT_NAME := utils

# Precompiled objects
PRECOMPILED_OBJECTS :=

# Include main makefile
include $(ROOT_PREFIX)subproj_makefile.mk
